
server:
  port: 8088

spring:
  datasource:
    # JDBC 配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.31.200.8:3307/dyups?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dyups
    password: dyups_2020
    # 连接池配置
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000

dyups:
  server: 10.103.61.45;10.103.61.37
  remotePath: /ext/dyups/conf.d/
  interfacePath: /upstream/
  interfacePort: 8081
  user: dyups
  password: tenginE@2020