package xyz.grafana.dyupspersistence.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table upstream_config
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UpstreamConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upstream_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   upstream名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upstream_config.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   备注说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upstream_config.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * Database Column Remarks:
     *   是否删除,1删除，0正常
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upstream_config.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upstream_config.id
     *
     * @return the value of upstream_config.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upstream_config.id
     *
     * @param id the value for upstream_config.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upstream_config.name
     *
     * @return the value of upstream_config.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upstream_config.name
     *
     * @param name the value for upstream_config.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upstream_config.comment
     *
     * @return the value of upstream_config.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upstream_config.comment
     *
     * @param comment the value for upstream_config.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upstream_config.is_delete
     *
     * @return the value of upstream_config.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upstream_config.is_delete
     *
     * @param isDelete the value for upstream_config.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}