package xyz.grafana.dyupspersistence.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table upstream_config
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UpstreamConfigWithBLOBs extends UpstreamConfig {
    /**
     * Database Column Remarks:
     *   upstream部分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upstream_config.upstream
     *
     * @mbg.generated
     */
    private String upstream;

    /**
     * Database Column Remarks:
     *   server部分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upstream_config.server
     *
     * @mbg.generated
     */
    private String server;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upstream_config.upstream
     *
     * @return the value of upstream_config.upstream
     *
     * @mbg.generated
     */
    public String getUpstream() {
        return upstream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upstream_config.upstream
     *
     * @param upstream the value for upstream_config.upstream
     *
     * @mbg.generated
     */
    public void setUpstream(String upstream) {
        this.upstream = upstream == null ? null : upstream.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upstream_config.server
     *
     * @return the value of upstream_config.server
     *
     * @mbg.generated
     */
    public String getServer() {
        return server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upstream_config.server
     *
     * @param server the value for upstream_config.server
     *
     * @mbg.generated
     */
    public void setServer(String server) {
        this.server = server == null ? null : server.trim();
    }
}